

export enum SECTION  {
    HERO = "HERO",
    WORK = "WORK",
    EDUCATION = "EDUCATION",
    SKILLS = "SKILLS",
    TESTIMONIALS = "TESTIMONIALS",
    PROJECTS = "PROJECTS",
    LANGUAGES = "LANGUAGES",
    CERTIFICATES = "CERTIFICATES",
    ACHIEVEMENTS = "ACHIEVEMENTS",
} 


export enum SETTINGS_TYPE {
    PAGINATION = "PAGINATION",
    ANIMATION = "ANIMATION",
    FEATURE = 'FEATURE',
}